### ISSUE TITLE
603 Too Many Contacts

### ISSUE THREAD

**Issue by FlandersBurger** [ringcentral/ringcentral-call-js#60]
I keep running into this error after initializing the RingCentralCal.
The webphone will work for a few phone calls but eventually runs into this. I have no idea what could be causing it and I don't find any information about it. 

"
SIP/2.0 603 Too Many Contacts
Via: SIP/2.0/WSS femcvfqh8p1f.invalid;branch=z9hG4bK6653901;received=24.108.116.162
To: <sip:1##########*101@sip.devtest.ringcentral.com>;tag=7BvYdcd7fcr
From: <sip:1##########*101@sip.devtest.ringcentral.com>;tag=vbdr8qojhl
Call-ID: 8frudde185qca0cgkkbrg1
CSeq: 3632 REGISTER
Content-Length: 0
"

**Comment by embbnux** [comment]
Link related issue https://github.com/ringcentral/ringcentral-web-phone/issues/374

**Comment by embbnux** [comment]
I am going to close this. 
Let's have the topic in RingCentral web phone sdk's issue link as this is not issue from this SDK.
